package com.rdev.rrepodocs.presentation.app

import com.rdev.rrepodocs.domain.model.DocumentEditState
import com.rdev.rrepodocs.domain.model.DocumentHistoryEntry
import com.rdev.rrepodocs.domain.model.DocumentShare
import com.rdev.rrepodocs.domain.model.MarkdownDocument
import com.rdev.rrepodocs.domain.model.RepoTreeNode
import com.rdev.rrepodocs.domain.model.ShareExpiryOption
import com.rdev.rrepodocs.domain.model.UserSession
import com.rdev.rrepodocs.domain.model.RepositoryRef

enum class AppMode {
    SignedOut,
    RepositorySelection,
    Workspace,
}

data class AppUiState(
    val mode: AppMode = AppMode.SignedOut,
    val session: UserSession? = null,
    val repositoryOptions: List<RepositoryRef> = emptyList(),
    val selectedRepository: RepositoryRef? = null,
    val showNonMarkdownFiles: Boolean = false,
    val repoTreeRoots: List<RepoTreeNode> = emptyList(),
    val expandedFolderPaths: Set<String> = emptySet(),
    val selectedExplorerPaths: Set<String> = emptySet(),
    val selectedMarkdownPath: String? = null,
    val activeDocument: MarkdownDocument? = null,
    val documentHistoryPath: String? = null,
    val documentHistory: List<DocumentHistoryEntry> = emptyList(),
    val documentHistoryLoading: Boolean = false,
    val documentHistoryError: String? = null,
    val documentHistoryLoadNonce: Int = 0,
    val documentEditState: DocumentEditState? = null,
    val pendingDocumentPath: String? = null,
    val documentLoading: Boolean = false,
    val documentError: String? = null,
    val documentLoadNonce: Int = 0,
    val loadedDocumentLoadNonce: Int = 0,
    val commitMessageDraft: String = "",
    val saveInProgress: Boolean = false,
    val saveError: String? = null,
    val saveSuccess: String? = null,
    val saveRequestNonce: Int = 0,
    val createDialogVisible: Boolean = false,
    val createTargetFolderDraft: String = "",
    val createFileNameDraft: String = "new-file.md",
    val createCommitMessageDraft: String = "Create new-file.md",
    val createRequestPath: String? = null,
    val createRequestContent: String = "",
    val createRequestCommitMessage: String = "",
    val createInProgress: Boolean = false,
    val createError: String? = null,
    val createRequestNonce: Int = 0,
    val createFolderDialogVisible: Boolean = false,
    val createFolderParentDraft: String = "",
    val createFolderNameDraft: String = "new-folder",
    val createFolderCommitMessageDraft: String = "Create new-folder",
    val createFolderRequestPath: String? = null,
    val createFolderRequestCommitMessage: String = "",
    val createFolderInProgress: Boolean = false,
    val createFolderError: String? = null,
    val createFolderRequestNonce: Int = 0,
    val renameDialogVisible: Boolean = false,
    val renameFileNameDraft: String = "",
    val renameCommitMessageDraft: String = "",
    val renameRequestPath: String? = null,
    val renameRequestCommitMessage: String = "",
    val renameInProgress: Boolean = false,
    val renameError: String? = null,
    val renameRequestNonce: Int = 0,
    val moveDialogVisible: Boolean = false,
    val moveDestinationFolderDraft: String = "",
    val moveCommitMessageDraft: String = "",
    val moveRequestSourcePath: String? = null,
    val moveRequestPath: String? = null,
    val moveRequestPaths: List<Pair<String, String>> = emptyList(),
    val moveRequestCommitMessage: String = "",
    val moveInProgress: Boolean = false,
    val moveError: String? = null,
    val moveRequestNonce: Int = 0,
    val copiedMarkdownPath: String? = null,
    val pasteRequestSourcePath: String? = null,
    val pasteRequestDestinationPath: String? = null,
    val pasteRequestCommitMessage: String = "",
    val pasteInProgress: Boolean = false,
    val pasteError: String? = null,
    val pasteRequestNonce: Int = 0,
    val deleteRequestPaths: List<String> = emptyList(),
    val deleteRequestCommitMessage: String = "",
    val deleteInProgress: Boolean = false,
    val deleteError: String? = null,
    val deleteRequestNonce: Int = 0,
    val shareDialogVisible: Boolean = false,
    val shareExpiryOption: ShareExpiryOption = ShareExpiryOption.ThirtyDays,
    val activeShare: DocumentShare? = null,
    val shareInProgress: Boolean = false,
    val shareError: String? = null,
    val shareRequestNonce: Int = 0,
    val pendingShareRevokeId: String? = null,
    val shareRevokeInProgress: Boolean = false,
    val shareRevokeError: String? = null,
    val shareRevokeRequestNonce: Int = 0,
    val sharedLinksDialogVisible: Boolean = false,
    val sharedLinks: List<DocumentShare> = emptyList(),
    val sharedLinksLoading: Boolean = false,
    val sharedLinksError: String? = null,
    val sharedLinksLoadNonce: Int = 0,
    val repoTreeLoading: Boolean = false,
    val repoTreeError: String? = null,
    val repoTreeLoadNonce: Int = 0,
    val repositoriesLoading: Boolean = false,
    val repositoriesError: String? = null,
    val repositoryLoadNonce: Int = 0,
)
